version: "3.9" 

services:
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app 
    volumes:
      - .:/app 
      - /app/node_modules 
    ports:
      - "3000:3000" 
